config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "home#index", as: "home"
  end
  unauthenticated :user do
    root 'static_pages#index'
  end

  resources :tweets, except: [:new, :edit] do
    member do
      post :reply
    end
  end
  resources :users, except: [:new, :create] do
    member do
      get 'followers'
      get 'following'
      get 'favorites'
      get 'retweets'
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  resources :find_friends, only: :index

end

app/views/partials/_avatar.html.erb
<%= link_to user_path(user) do %>
  <%= image_tag user.avatar.url || 'avatar.jpg', class: klass %>
<% end %>

app/views/partials/_devise_form_errors.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= resource.errors.full_messages.first %>
  </div>
<% end %>

app/views/partials/_error_message.html.erb
<% if error_message %>
  <div class="alert alert-dismissable alert-fixed alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= error_message %>
  </div>
<% end %>

app/views/partials/_follow.html.erb
<% if following?(user) %>
  <%= link_to fa_icon("check"), relationship_path(current_user.relationships.find_by_friend_id(user)), method: :delete, remote: true, class: 'btn btn-success' %>
<% else %>
  <%= link_to fa_icon("user-plus").html_safe, relationships_path(friend_id: user.id), method: :post, remote: true, class: 'btn btn-primary' %>
<% end %>

app/views/partials/_image_upload.html.erb
<div class="modal fade" id="image-upload-modal" tabindex="-1" role="dialog" aria-labelledby="imageUploadLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Media Upload</h4>
      </div>
      <div class="modal-body">
        <%= form_tag media_path, method: :post, class: "dropzone", id: "media-dropzone" do %>
          <div class="fallback">
            <%= file_field_tag :image, multiple: false %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_load_more.html.erb
<div id="loader", class="well text-center hidden">
  <%= image_tag "ajax-loader.gif" %>
  <%= will_paginate items %>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" style="background-color:#fff;">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="/assets/Micro-logo2.png" alt="Micro">
        </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      

        <% if user_signed_in? %>
          
          <li>
            <a href="#", class="profile-image dropdown-toggle" data-toggle="dropdown", role="button", aria-expanded="false">
              <%= image_tag current_user.avatar, class: "avatar-xs" %>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "#{current_user.name}<br><b>@#{current_user.username}</b>".html_safe, user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to("Find Friends", find_friends_path) %></li>
              <li><%= link_to "Settings", user_path(current_user) %></li>
              <li><%= link_to('Sign out', destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
          <form class="navbar-form navbar-right">
            <button id="new-tweet" type="button" data-toggle="modal" data-target="#new-tweet-modal" class="btn btn-danger"> Share... </button>
          </form>
        <% end %>
      </ul>
    </div>
  </div>
</form>
</nav>
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<div id="flipkart-navbar">
    <div class="container">
        <div class="row row1">
            <ul class="largenav">
                <li class="upper-links"><a class="links" href="http://clashhacks.in/">#DGB</a></li>
                <li class="upper-links"><a class="links" href="https://campusbox.org/">#STEEM</a></li>
                <li class="upper-links"><a class="links" href="http://clashhacks.in/">#FLDC</a></li>
                <li class="upper-links"><a class="links" href="http://clashhacks.in/">#BTC</a></li>
                <li class="upper-links"><a class="links" href="http://clashhacks.in/">#ETH</a></li>
                <li class="upper-links"><a class="links" href="http://clashhacks.in/">#XRP</a></li>
                <li class="upper-links"><a class="links" href="http://clashhacks.in/">#POT</a></li>
                <li class="upper-links"><a class="links" href="https://campusbox.org/">#STORJ</a></li>
                <li class="upper-links"><a class="links" href="http://clashhacks.in/">#FLDC</a></li>
                <li class="upper-links"><a class="links" href="http://clashhacks.in/">#BTC</a></li>
                <li class="upper-links"><a class="links" href="http://clashhacks.in/">#ETH</a></li>
                <li class="upper-links"><a class="links" href="http://clashhacks.in/">#XRP</a></li>
                <li class="upper-links"><a class="links" href="http://clashhacks.in/">#XRP</a></li>
                <li class="upper-links"><a class="links" href="http://clashhacks.in/">#POT</a></li>
                <li class="upper-links"><a class="links" href="https://campusbox.org/">#STORJ</a></li>
                 <li class="upper-links"><a class="links" href="http://clashhacks.in/">#BTC</a></li>
                
                

               
                    
                </li>
                
            </ul>
        </div>
        <div class="row row2">
            <div class="col-sm-2">
               
            </div>
            <div class="flipkart-navbar-search smallsearch col-sm-8 col-xs-11">
                <div class="row">
                    <input class="flipkart-navbar-input col-xs-11" type="" placeholder="Search coins, traders, and more..." name="">
                    <button class="flipkart-navbar-button col-xs-1">
                        <svg width="15px" height="15px">
                            <path d="M11.618 9.897l4.224 4.212c.092.09.1.23.02.312l-1.464 1.46c-.08.08-.222.072-.314-.02L9.868 11.66M6.486 10.9c-2.42 0-4.38-1.955-4.38-4.367 0-2.413 1.96-4.37 4.38-4.37s4.38 1.957 4.38 4.37c0 2.412-1.96 4.368-4.38 4.368m0-10.834C2.904.066 0 2.96 0 6.533 0 10.105 2.904 13 6.486 13s6.487-2.895 6.487-6.467c0-3.572-2.905-6.467-6.487-6.467 "></path>
                        </svg>
                    </button>
                </div>
            </div>
            
        </div>
    </div>
</div>
<div id="mySidenav" class="sidenav">
    <div class="container" style="background-color: #2874f0; padding-top: 10px;">
        <span class="sidenav-heading">Home</span>
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
    </div>
    <a href="http://clashhacks.in/">#DGB</a>
    <a href="http://clashhacks.in/">#NAV</a>
    <a href="http://clashhacks.in/">#ETH</a>
    <a href="http://clashhacks.in/">#STEEM</a>
    <a href="http://clashhacks.in/">#FLDC</a>
    <a href="http://clashhacks.in/">#ETHC</a>
    <a href="http://clashhacks.in/">#XRP</a>
</div>

app/views/partials/_new_tweet.html.erb
<%= form_tag tweets_path(parent_id: tweet_id), multipart: true, method: :post, remote: true do %>
  <div class="form-group">
    <%= text_area_tag "tweet[tweet_text]", nil, class: "form-control", placeholder: "Share something..." %>
  </div>
  <div class="form-group hidden">
    <img id="tweet-img-preview">
    <a id="remove-tweet-img" href="#">&times;</a>
  </div>
  <div class="form-group">
    <%= hidden_field_tag "tweet[location]", nil %>
  </div>
  <div class="form-group">
    <%= file_field_tag "tweet[media]", class: "hidden", id: "media-upload-btn" %>
    <%= button_tag id: "tweet", class: "btn btn-success" do %>
      <%= fa_icon "lightbulb-o" %> Share
    <% end %>
    <div class="pull-right">
      <span id="tweet-count">140</span>
      <a id="ps-media-upload-btn" href="javascript:void(0);" class="btn btn-default">
        <i class="fa fa-camera"></i>
      </a>
     
    </div>
  </div>
<% end %>
<div id="tweet-error">
  <%= render 'partials/error_message', error_message: nil %>
</div>

app/views/partials/_reply_tweet.html.erb
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">
    <%= form_tag tweets_path(parent: tweet), method: :post, remote: true do %>
      <div class="form-group">
        <%= text_area_tag 'tweet[tweet_text]', "@#{tweet.user.username}", class: 'form-control', placeholder: 'Enter Reply' %>
      </div>
      <div class="form-group">
        <%= submit_tag 'Reply', id: 'tweet', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', '#', class: 'btn btn-primary cancel-reply', onclick: 'removeParent(this);', "data-tweet": tweet.id %>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_tweet_modal.html.erb
<div class="modal fade" id="new-tweet-modal" tabindex="-1" role="dialog" aria-labelledby="new-tweet-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Compose New Micro</h4>
      </div>
      <div class="modal-body">
        <%= render 'partials/new_tweet', tweet_id: nil %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_user_info.html.erb
<div class="card">
  <div class="cover" data-cover="<%= user.cover %>">
    <%= image_tag user.avatar, class: "avatar" %>
  </div>
  <div class="about">
    <h3 class="name"><%= user.name %></h3>
    <h5 class="username"><b>@<%= user.username %></b></h5>
    <span class="content"><%= user.about %></span>
    <% if view_type == 'profile' %>
      <div class="row">
        <% unless @user.location.blank? %>
          <h5><i class="fa fa-map-marker"></i> <%= @user.location %></h5>
        <% end %>
        <% unless @user.website.blank? %>
          <h5><i class="fa fa-link"></i> <%= link_to @user.website, @user.website %></h5>
        <% end %>
        <h5><i class="fa fa-clock-o"></i> Joined <%= formatted_time(@user.created_at) %></h5>
      </div>
    <% else %>
      <div class="stats">
        <div class="row">
          <div class="col-lg-4 text-center">
            <%= link_to user_path(user) do %>
              <h5><b>Posts</b></h5>
              <h4 id="tweets-count"><%= user.tweets_count %></h4>
            <% end %>
          </div>
          <div class="col-lg-4 text-center">
            <%= link_to followers_user_path(user) do %>
              <h5><b>Followers</b></h5>
              <h4 id="followers-count"><%= user.followers_count %></h4>
            <% end %>
          </div>
          <div class="col-lg-4 text-center">
            <%= link_to following_user_path(user) do %>
              <h5><b>Following</b></h5>
              <h4 id="following-count"><%= user.following_count %></h4>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>